name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        splat: ['1', '2', '3', '4', '5', '6', '7', '8', '9']

    steps:
    - uses: actions/checkout@v2
    - name: info
      run: ./info
    - name: make
      run: make factorial
    - name: run
      run: ./factorial
